import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
const deps = vi.hoisted(() => ({ loadSettings: vi.fn(), patchSettings: vi.fn(), broadcast: vi.fn(), subscribe: vi.fn(), isLyricWindowOpen: vi.fn() }));
vi.mock('@lx/tauri-bridge', () => ({ ...deps, setLyricWindowPinned: vi.fn() }));
vi.mock('@/stores/lyricSettingsSync', () => ({ broadcastLyricSettings: deps.broadcast, subscribeLyricSettings: deps.subscribe }));
vi.mock('@/utils/desktopLyricToggle', () => ({ toggleDesktopLyricFromPlayer: vi.fn() }));
import { DesktopLyricSettingsSection } from '../src/views/settings/DesktopLyricSettingsSection';
let renderer: ReactTestRenderer;
let onPatch: (patch: object) => void;
const control = (label: string) => renderer.root.findAllByProps({ className: 'af-setting-row' }).find(row => row.findByProps({ className: 'af-setting-row-label' }).children[0] === label)?.findByType('input');
beforeEach(() => {
  vi.resetAllMocks();
  deps.loadSettings.mockResolvedValue({ lyricShowRomanization: false, lyricShowRuby: false });
  deps.patchSettings.mockResolvedValue(undefined);
  deps.isLyricWindowOpen.mockResolvedValue(false);
  deps.subscribe.mockImplementation(handler => { onPatch = handler; return () => {}; });
});
afterEach(() => act(() => renderer?.unmount()));
it('两个默认关闭的独立设置持久化、广播，说明同时影响沉浸及桌面', async () => {
  await act(async () => { renderer = create(<DesktopLyricSettingsSection />); });
  expect(control('显示罗马音')).toBeDefined();
  expect(control('显示注音')).toBeDefined();
  expect(control('显示罗马音')!.props.checked).toBe(false);
  expect(control('显示注音')!.props.checked).toBe(false);
  expect(JSON.stringify(renderer.toJSON())).toContain('同时影响沉浸式及桌面歌词');
  await act(async () => { await control('显示罗马音')!.props.onChange({ target: { checked: true } }); });
  expect(deps.patchSettings).toHaveBeenCalledWith({ lyricShowRomanization: true });
  expect(deps.broadcast).toHaveBeenCalledWith({ lyricShowRomanization: true });
  expect(control('显示注音')!.props.checked).toBe(false);
  await act(async () => { await control('显示注音')!.props.onChange({ target: { checked: true } }); });
  expect(deps.patchSettings).toHaveBeenCalledWith({ lyricShowRuby: true });
  act(() => onPatch({ lyricShowRomanization: false, lyricShowRuby: false }));
  expect(control('显示罗马音')!.props.checked).toBe(false);
  expect(control('显示注音')!.props.checked).toBe(false);
});
it('重新挂载读取已持久化开关', async () => {
  deps.loadSettings.mockResolvedValue({ lyricShowRomanization: true, lyricShowRuby: true });
  await act(async () => { renderer = create(<DesktopLyricSettingsSection />); });
  expect(control('显示罗马音')?.props.checked).toBe(true);
  expect(control('显示注音')?.props.checked).toBe(true);
});
